### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by phanthuthao** [fr4nc1stein/osint-framework#57]
osif email(hunter_email) > set DOMAIN google.com                                                                                                                       
[+] DOMAIN => google.com
osif email(hunter_email) > run                                                                                                                                         

Analyzing 'google.com'...
[-] 'data'
KeyError: 'data'

**Comment by fr4nc1stein** [comment]
This module requires hunter.io API key. Did you register and use it?
Please check the docs.
