### ISSUE TITLE
ModuleNotFoundError: No module named 'censys.search'; 'censys' is not a package

### ISSUE THREAD

**Issue by R1punk** [fr4nc1stein/osint-framework#70]
help me

![Screenshot from 2023-08-14 11-11-27](https://github.com/fr4nc1stein/osint-framework/assets/84296947/ea56ec13-e322-4216-bbbe-cf6e11a4bc6f)

**Comment by fr4nc1stein** [comment]
Did you try to `pip3 install -r requirements.txt`?

**Comment by kamuluzo** [comment]
Same problem here. I tried it (in Ubuntu VM) with normal installation and again with docker. I get same error

Greetz Henry

**Comment by fr4nc1stein** [comment]
Hi @kamuluzo  we remove temporarily the Censys module, it fixed here #75

Master branch is now updated.
